export const techIcons = [
  { name: "Aws", src: "/tech-icons2/aws.png" },
  { name: "CPP", src: "/tech-icons2/cpp.png" },
  { name: "CSS", src: "/tech-icons2/css.png" },
  { name: "Dart", src: "/tech-icons2/dart.png" },
  { name: "Docker", src: "/tech-icons2/docker.png" },
  { name: "Figma", src: "/tech-icons2/figma.png" },
  { name: "Flutter", src: "/tech-icons2/flutter.png" },
  { name: "Git", src: "/tech-icons2/git.png" },
  { name: "Github", src: "/tech-icons2/github.png" },
  { name: "Html5", src: "/tech-icons2/html.png" },
  { name: "Javascript", src: "/tech-icons2/javascript.png" },
  { name: "Nextjs", src: "/tech-icons2/nextjs.png" },
  { name: "OpenAI", src: "/tech-icons2/openai.png" },
  { name: "PostgreSQL", src: "/tech-icons2/postgres.png" },
  { name: "Reactjs", src: "/tech-icons2/reactjs.png" },
  { name: "TailwindCSS", src: "/tech-icons2/tailwindcss.png" },
  { name: "VSCode", src: "/tech-icons2/vscode.png" },
  { name: "WordPress", src: "/tech-icons2/wordpress.png" },
];