// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  code_block: dynamic(() => import("./CodeBlock")),
  image_block: dynamic(() => import("./ImageBlock")),
  rich_text_content: dynamic(() => import("./RichTextContent")),
  table: dynamic(() => import("./Table")),
};
